import type { Rng } from "./rng";

export function sampleUniform(rng: Rng, a: number, b: number): number {
  if (!Number.isFinite(a) || !Number.isFinite(b) || a >= b) {
    throw new Error("Uniform requires finite a < b");
  }
  return a + (b - a) * rng.nextU01();
}

export type NormalSampler = (rng: Rng, mu: number, sigma: number) => number;

/**
 * Creates a Box-Muller normal sampler with its own `spare` state.
 *
 * The spare half of each Box-Muller pair must NOT be shared across independent
 * simulation runs: doing so leaks a value generated by one RNG stream into
 * another, which breaks seeded reproducibility and contaminates samples.
 * Create one sampler per run so each RNG stream owns its spare.
 */
export function createNormalSampler(): NormalSampler {
  let spare: number | null = null;
  return function sampleNormal(rng: Rng, mu: number, sigma: number): number {
    if (!Number.isFinite(mu) || !Number.isFinite(sigma) || sigma <= 0) {
      throw new Error("Normal requires finite mu and sigma > 0");
    }

    if (spare !== null) {
      const z = spare;
      spare = null;
      return mu + sigma * z;
    }

    let u = 0;
    let v = 0;
    let s = 0;
    do {
      u = 2 * rng.nextU01() - 1;
      v = 2 * rng.nextU01() - 1;
      s = u * u + v * v;
    } while (s <= 0 || s >= 1);

    const mul = Math.sqrt((-2 * Math.log(s)) / s);
    spare = v * mul;
    return mu + sigma * (u * mul);
  };
}

// Backwards-compatible module-level sampler. Prefer `createNormalSampler()` for
// any code that depends on reproducibility across independent RNG streams.
const defaultNormalSampler = createNormalSampler();
export function sampleNormal(rng: Rng, mu: number, sigma: number): number {
  return defaultNormalSampler(rng, mu, sigma);
}

export function samplePoisson(rng: Rng, lambda: number): number {
  if (!Number.isFinite(lambda) || lambda <= 0) {
    throw new Error("Poisson requires finite lambda > 0");
  }

  if (lambda < 30) {
    const L = Math.exp(-lambda);
    let p = 1;
    let k = 0;
    do {
      k += 1;
      p *= rng.nextU01();
    } while (p > L);
    return k - 1;
  }

  const normalApprox = Math.round(sampleNormal(rng, lambda, Math.sqrt(lambda)));
  return Math.max(0, normalApprox);
}

/**
 * Binomial(n, p): number of successes in n independent Bernoulli(p) trials.
 * Sampled by counting n direct Bernoulli draws — the textbook definition. The
 * trial counts here (per-hour arrivals/acceptances) are small, so the linear
 * count is efficient and exact. Bernoulli(p) is just Binomial(1, p).
 */
export function sampleBinomial(rng: Rng, n: number, p: number): number {
  if (!Number.isInteger(n) || n < 0) {
    throw new Error("Binomial requires an integer n >= 0");
  }
  if (!Number.isFinite(p) || p < 0 || p > 1) {
    throw new Error("Binomial requires 0 <= p <= 1");
  }
  let successes = 0;
  for (let i = 0; i < n; i++) {
    if (rng.nextU01() < p) successes += 1;
  }
  return successes;
}
